# -*- coding: utf-8 -*-
"""analysis_combined_terrain.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sSMS-yFS8ZTSrb6W8gQDFtL259oEYVNv
"""

import numpy as np
import matplotlib.pyplot as plt
from subfunctions import F_net, get_gear_ratio

# ---- ROV!!
rover = {'wheel_assembly': wheel_assembly, 'chassis': chassis,
         'science_payload': science_payload, 'power_subsys': power_subsys}
# ---- Planet
planet = {'g': 3.72}

Crr_array = np.linspace(0.01,0.5,25)
slope_array_deg = np.linspace(-15,35,25)

CRR, SLOPE = np.meshgrid(Crr_array, slope_array_deg)

VMAX = np.zeros(np.shape(CRR), dtype= float) #25x25 matrix

for i in range(np.shape(CRR)[0]):
    for j in range(np.shape(CRR)[1]):
      omega_low = 0
      omega_high = 3.8
      Crr_sample = float(CRR[i,j])
      slope_sample = float(SLOPE[i,j])

      while abs(omega_high - omega_low) > 1e-5:
        omega_center = (omega_high + omega_low)/2

        if F_net(omega_low, slope_sample, rover, planet, Crr_sample) * F_net(omega_center, slope_sample, rover, planet, Crr_sample) <= 0:
          omega_high = omega_center
        else:
          omega_low = omega_center

      omega = (omega_high + omega_low)/2

      Ng = get_gear_ratio(rover['speed_reducer'])
      omega_wheel = omega / Ng
      VMAX[i,j] = 0.30 * omega_wheel
