# -*- coding: utf-8 -*-
"""analysis_rolling_resistance.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLwC_XEyJNB_YuO_VAQ5uP-4HpYR3yAK
"""

#root finding method to determine speed of rover at various values for coefficient of rolling resistance
#slope = 0
import numpy as np
from subfunctions import F_net, get_gear_ratio
import matplotlib.pyplot as plt

# Emily BWM

# ---- Wheel
wheel = {'mass': 1.0, 'radius': 0.3}
# ---- Speed Reducer
speed_reducer = {'type': 'reverted', 'diam_pinion': 0.04,
                  'diam_gear': 0.07, 'mass': 1.5}
# ---- Motor
motor = {'torque_stall': 170.0, 'torque_noload': 0.0,
         'speed_noload': 3.80, 'mass': 5.0}
# ---- Chassis
chassis = {'mass': 659.0}
# ---- SP
science_payload = {'mass': 75.0}
# ---- Power Subsystem
power_subsys = {'mass': 90.0}
# ---- Wheel Assembly
wheel_assembly = {'wheel': wheel, 'speed_reducer': speed_reducer, 'motor': motor}
# ---- ROV!!
rover = {'wheel_assembly': wheel_assembly, 'chassis': chassis,
         'science_payload': science_payload, 'power_subsys': power_subsys}
# ---- Planet
planet = {'g': 3.72}

Crr_array = np.linspace(0.01, 0.5, 25)

v_max = np.zeros(np.shape(Crr_array), dtype=float) # array place holder type float

#Get vals for v_max and plot it against Crr_array

for i in range(len(Crr_array)):

    Crr = Crr_array[i]
    slope = 0
    omega_low = 0
    omega_high = 3.8

    if F_net(omega_low, slope, rover, planet, Crr) * F_net(omega_high, slope, rover, planet, Crr) <= 0:

        while abs(omega_high - omega_low) > 1e-5:

            omega_center = (omega_high + omega_low)/2

            if F_net(omega_low, slope, rover, planet, Crr) * F_net(omega_center, slope, rover, planet, Crr) <= 0:
                omega_high = omega_center
            else:
                omega_low = omega_center

        omega = (omega_high + omega_low)/2

        Ng = get_gear_ratio(rover['wheel_assembly']['speed_reducer'])
        omega_wheel = omega / Ng
        v_max[i] = 0.30 * omega_wheel

    else:
        v_max[i] = np.nan # no root

plt.plot(Crr_array, v_max)
plt.xlabel("Coefficient of Rolling Resistance")
plt.ylabel("Maximum Rover Velocity [m/s]")
plt.show()
