# -*- coding: utf-8 -*-
"""graphs_sr.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JGupiJEdxwWDzSDNeeiKLYZ3m2QcD08i
"""

import numpy as np
import matplotlib.pyplot as plt
import subfunctions as sf
omega = np.linspace(0, 3.80, 100)
motor = sf.motor
torque_in = sf.tau_dcmotor(omega,motor)
speed_reducer = sf.speed_reducer
Ng = sf.get_gear_ratio(speed_reducer)
torque_out = torque_in * Ng
omega_out = omega/Ng
power_out = omega * torque_out

plt.figure(figsize=[8,6])

plt.subplot(3,1,1)
plt.plot(torque_out, omega_out)
plt.xlabel('Motor Shaft Torque (N/m) ')
plt.ylabel('Motor Speed (rad/s)')

plt.subplot(3,1,2)
plt.plot(torque_out, power_out)
plt.xlabel('Motor Shaft Torque (N/m) ')
plt.ylabel('Motor Power (W)')

plt.subplot(3,1,3)
plt.plot(omega_out,torque_out)
plt.xlabel('Motor Speed (rad/s')
plt.ylabel('Motor Shaft Torque (N/m)')

plt.show()
