# -*- coding: utf-8 -*-
"""subfunctions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8BduGcYnkq6Pt0yMkLLnCv-aV8-6DWO
"""

# Emily BWM

# ---- Wheel
wheel = {'mass': 1.0, 'radius': 0.3}
# ---- Speed Reducer
speed_reducer = {'type': 'reverted', 'diam_pinion': 0.04,
                  'diam_gear': 0.07, 'mass': 1.5}
# ---- Motor
motor = {'torque_stall': 170.0, 'torque_noload': 0.0,
         'speed_noload': 3.80, 'mass': 5.0}
# ---- Chassis
chassis = {'mass': 659.0}
# ---- SP
science_payload = {'mass': 75.0}
# ---- Power Subsystem
power_subsys = {'mass': 90.0}
# ---- Wheel Assembly
wheel_assembly = {'wheel': wheel, 'speed_reducer': speed_reducer, 'motor': motor}
# ---- ROV!!
rover = {'wheel_assembly': wheel_assembly, 'chassis': chassis,
         'science_payload': science_payload, 'power_subsys': power_subsys}
# ---- Planet
planet = {'g': 3.72}

# Emily BWM
# make sure to do the debuging, he expects us to figure out what he mistyped

def get_mass(rover):
  m = 0
  if type(rover) is not dict:
    raise Exception('Invalid input: rover must be a dict')
  else:
    wheel_assembly_mass = rover['wheel_assembly']['wheel']['mass'] + \
    rover['wheel_assembly']['speed_reducer']['mass'] +\
    rover['wheel_assembly']['motor']['mass']
    chassis_mass = rover['chassis']['mass']
    science_payload_mass = rover['science_payload']['mass']
    power_subsys_mass = rover['power_subsys']['mass']
    m += 6*wheel_assembly_mass + chassis_mass + science_payload_mass + power_subsys_mass
  return m

#Hailey Reyes

def get_gear_ratio(speed_reducer):

  if not isinstance(speed_reducer, dict):
    raise Exception('Input must be a dictionary.')

  if speed_reducer['type'].lower() != "reverted":
    raise Exception('Type must be reverted.')

  Ng = (speed_reducer['diam_gear']/speed_reducer['diam_pinion'])**2

  return Ng

#Hailey Reyes

import numpy as np
from scipy.special import erf

def F_rolling(omega, terrain_angle, rover, planet, Crr):

  omega = np.asarray(omega)
  terrain_angle = np.asarray(terrain_angle)
  if omega != terrain_angle:
    raise Exception('omega and terrain angle must be same size')

  if np.any(terrain_angle) < -75 or np.any(terrain_angle) > 75:
    raise Exception('terrain_angle must be in between -75 and 75 degrees')

  if not isinstance(rover,dict):
    raise Exception('rover must be a dictionary')

  if not isinstance(planet, dict):
    raise Exception('planet must be a dictionary')

  if Crr <=0:
    raise Exception('Crr must be positive')

  Ng = get_gear_ratio(rover['wheel_assembly']['speed reducer'])
  r = rover['wheel_assembly']['wheel']['radius']
  v_rover = (omega*r)/Ng
  m = get_mass(rover)

  Frr = erf(40*v_rover)*Crr*m*planet['g']*np.cos(np.radians(terrain_angle))

  return Frr

#Hailey Reyes

def F_gravity(terrain_angle,rover,planet):
  m = get_mass(rover)
  g = planet['g']
  terrain_angle = np.asarray(terrain_angle)
  if not isinstance(planet, dict):
    raise Exception('planet must be a dictionary')
  elif not isinstance(rover, dict):
    raise Exception('rover must be a dictionary')
  elif np.any(terrain_angle < -75) or np.any(terrain_angle > 75):
    raise Exception('terrain_angle must be between -75 and 75 degrees')

  Fgt = -m*g*np.sin(np.radians(terrain_angle))

  return Fgt

#Emily BWM

# torque structure
# motor = {'torque_stall': 170.0, 'torque_noload': 0.0,
#          'speed_noload': 3.80, 'mass': 5.0}

import numpy as np
def tau_dcmotor(omega, motor):
  if not isinstance(omega, (int, float, np.ndarray)):
    raise Exception('Invalid input. Not a scalar')
  if not isinstance(motor, dict):
    raise Exception('Invalid input. Not a vector')
  if isinstance(omega, np.ndarray) and omega.ndim != 1:
    raise Exception('Invalid input: omega must be a scalar or a 1D array')

  if isinstance(omega, np.ndarray):
    tau = np.zeros(len(omega))
    for i in range(len(omega)):
      if omega[i] > motor['speed_noload']: #spinning faster
            tau[i] = 0.0
      elif omega[i] < 0:
            tau[i] = motor['torque_stall']
      else:
        tau[i] = motor['torque_stall'] - (((motor['torque_stall']-motor['torque_noload'])/(motor['speed_noload']))*omega[i]) #Torque at motor shaft
    return tau
  else:
    if omega > motor['speed_noload']:
      tau = 0.0
    elif omega < 0:
      tau = motor['torque_stall']
    else:
      tau = motor['torque_stall'] - (((motor['torque_stall']-motor['torque_noload'])/(motor['speed_noload']))*omega)
    return float(tau)

#Emily BWM
## ---- Motor
#motor = {'torque_stall': 170.0, 'torque_noload': 0.0,
#         'speed_noload': 3.80, 'mass': 5.0}
#
# F_tot = 6F_wheel
# F_wheel = tau_wheel/r_wheel
def F_drive(omega, rover):
  if not isinstance(omega, (int, float, np.ndarray)):
        raise Exception('Invalid input. Not a scalar or vector')
  if not isinstance(rover, dict):
        raise Exception('Invalid input: rover must be a dict')
  ratio = get_gear_ratio(rover['wheel_assembly']['speed_reducer'])
  tau = tau_dcmotor(omega, rover) #get motor torque
  tau_wheel = tau*ratio
  F_wheel = tau_wheel/rover['wheel']['radius']
  Fd = 6*F_wheel

  return Fd

#Hailey Reyes

def F_net(omega,terrain_angle,rover,planet,Crr):

  omega = np.asarray(omega)
  terrain_angle = np.asarray(terrain_angle)

  if terrain_angle.size != omega.size:
    raise Exception('omega and terrain_angle must be the same size')
  if np.any(terrain_angle < -75) or np.any(terrain_angle > 75):
    raise Exception('terrain_angle must be between -75 and 75 degrees')
  if not isinstance(rover, dict):
    raise Exception('rover must be a dictionary')
  if not isinstance(planet, dict):
    raise Exception('planet must be a dictionary')
  if Crr <= 0:
    raise Exception('Crr must be positive')

  Fd = F_drive(omega,rover)
  Fg = F_gravity(terrain_angle,rover,planet)
  Frr = F_rolling(omega,terrain_angle,rover,planet,Crr)

  Fnet = Fd + Fg + Frr

  return Fnet
