# -*- coding: utf-8 -*-
"""analysis_terrain_slope.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PSBTgSSNRoguW74L9-Wt-fpYVPMlRfJJ
"""



#Emily BWM
#root-finding method (e.g., bisection method, secant method, etc.) to determine the speed of the rover at various terrain slopes.
# F net = 0 so F net is required to be called
#*** Hint: Since we are not using a speed controller in this model, your rover will travel at the fastest speed it can in any given situation.
#Its top speed is the velocity it is at when it stops accelerating. This means you must look for the operating point of the motor at which the net force acting on the rover is zero. *** • Hint: You can use the no-load and stall speeds of the motor to define an initial bracket for a rootfinding method. Alternatively, provide an open method with any value on this range.
import numpy
import matplotlib.pyplot
from subfunctions import F_net, get_gear_ratio

# Emily BWM

# ---- Wheel
wheel = {'mass': 1.0, 'radius': 0.3}
# ---- Speed Reducer
speed_reducer = {'type': 'reverted', 'diam_pinion': 0.04,
                  'diam_gear': 0.07, 'mass': 1.5}
# ---- Motor
motor = {'torque_stall': 170.0, 'torque_noload': 0.0,
         'speed_noload': 3.80, 'mass': 5.0}
# ---- Chassis
chassis = {'mass': 659.0}
# ---- SP
science_payload = {'mass': 75.0}
# ---- Power Subsystem
power_subsys = {'mass': 90.0}
# ---- Wheel Assembly
wheel_assembly = {'wheel': wheel, 'speed_reducer': speed_reducer, 'motor': motor}
# ---- ROV!!
rover = {'wheel_assembly': wheel_assembly, 'chassis': chassis,
         'science_payload': science_payload, 'power_subsys': power_subsys}
# ---- Planet
planet = {'g': 3.72}

Crr = 0.15
slope_array_deg = numpy.linspace(-15, 35, 25) # Degrees!
v_max = numpy.zeros(numpy.shape(slope_array_deg), dtype=float) # array place holder type float

for i in range(len(slope_array_deg)):
    slope = slope_array_deg[i]
    omega_low = 0
    omega_high = 3.8

    if F_net(omega_low, slope, rover, planet, Crr) * F_net(omega_high, slope, rover, planet, Crr) <= 0:

        while abs(omega_high - omega_low) > 1e-5:
            omega_center = (omega_high + omega_low)/2

            if F_net(omega_low, slope, rover, planet, Crr) * F_net(omega_center, slope, rover, planet, Crr) <= 0:
                omega_high = omega_center
            else:
                omega_low = omega_center

        omega = (omega_high + omega_low)/2

        Ng = get_gear_ratio(rover['speed_reducer'])
        omega_wheel = omega / Ng
        v_max[i] = 0.30 * omega_wheel

    else:
        v_max[i] = numpy.nan

matplotlib.pyplot.plot(slope_array_deg, v_max)
matplotlib.pyplot.xlabel("Terrain Slope [deg]")
matplotlib.pyplot.ylabel("Maximum Rover Velocity [m/s]")
matplotlib.pyplot.show()
