# -*- coding: utf-8 -*-
"""graphs_motor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M20mccZJrIYd-lqO3cwlpYRZ76BProGO
"""

import numpy as np
import matplotlib.pyplot as plt
import subfunctions as sf

torque = sf.tau_dcmotor(omega,motor)
power = omega * torque

plt.figure()

plt.subplot(3,1,1)
plt.plot(omega,torque)
plt.xlabel('Motor Shaft Speed (rad/s)')
plt.ylabel('Motor Shaft Torque (N/m)')

plt.subplot(3,1,3)
plt.plot(torque,power)
plt.xlabel('Motor Shaft Torque (N/m)')
plt.ylabel('Motor Power (W)')

plt.subplot(3,1,2)
plt.plot(omega,power)
plt.xlabel('Motor Shaft Speed (rad/s)')
plt.ylabel('Motor Power (W)')

plt.show()